### ISSUE TITLE
What happened to the project?

### ISSUE THREAD

**Issue by nikandfor** [boltlang/Bolt#27]
I'm reading the "CREATING THE BOLT COMPILER" post series and with README it looks very interesting to try or read the code. What happened to the project?

**Comment by samvv** [comment]
`CREATING THE BOLT COMPILER` is a post series I never wrote. I'm suspecting you're actually looking for [this project](https://github.com/mukul-rathi/bolt), which happens to have the same name as this project.

Does that help?

**Comment by nikandfor** [comment]
Yes, I think this is the project I was looking for. Thank you!

What happened to your language though?

**Comment by samvv** [comment]
The project has been put on hold until I'm more comfortable with the type inference allgorithms underlying much of the more advanced type systems. Unfortunately it's not easy to self-study these materials, but that's part of the reason why I created samvv/learn-type-inference. Reminds me that I need to push some changes to that repository ...

**Comment by samvv** [comment]
Going to close this issue. I've just open-sourced the latest version of the compiler to `master`, so it should be clear what this project is doing.
